#! python


def build(ctx):

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    ctx(
        features='run_py_script',
        source='get_simulation_draws.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
        name='get_simulation_draws'
    )

    ctx(
        features='run_do_script',
        source='data_prep_lc.do',
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_prep_lc.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'LoanStats_all.dta')
        ],
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3a.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3b.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3c.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3d.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q2.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q3.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q4.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q2.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q3.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q4.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2018Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2018Q2.csv'),
            out_models('data_prep.do')
        ],
    )
