#! python

import os


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    ctx(
        features='run_py_script',
        source='get_simulation_draws.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
        name='get_simulation_draws'
    )

    abspath = os.path.join(ctx.path.abspath(), 'test_cleaner.py')
    ctx(
        features='run_py_script',
        source='test_cleaner.py',
        deps=[
            ctx.path_to(ctx, 'IN_MODEL_CODE', 'data_cleaner.py'),
            ctx.path_to(ctx, 'IN_MODEL_SPECS', 'state_names.json')
        ],
        append=abspath
    )

    ctx(
        features='run_do_script',
        source='data_prep_lc.do',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3a.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3b.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3c.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats3d.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q2.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q3.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2016Q4.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q2.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q3.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2017Q4.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2018Q1.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'LoanStats_2018Q2.csv'),
            out_models('file_names.do')
        ],
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_prep_lc.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'LoanStats_all.dta')
        ],
    )

    ctx(
        features='run_do_script',
        source='data_prep_bankloan.do',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'area_report_by_year.xlsx'),
            out_models('file_names.do')
        ],
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_prep_bankloan.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'bankloan.dta')
        ],
    )

    for year in ['2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']:
        ctx(
            features='subst',
            source='data_prep_sod.do',
            target='data_prep_sod_{}.do'.format(year)
        )
        ctx(
            features='run_do_script',
            source='data_prep_sod_{}.do'.format(year),
            deps=[
                ctx.path_to(ctx, 'IN_DATA', 'bank-data.csv'),
                ctx.path_to(ctx, 'IN_DATA', 'ALL_{}.csv'.format(year))
            ],
            target=[
                ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_prep_sod_{}.log'.format(year)),
                ctx.path_to(ctx, 'OUT_DATA', 'sod_{}.dta'.format(year))
            ],
            name='data_prep_sod_{}'.format(year),
            append=year
        )
    ctx(
        features='run_do_script',
        source='data_prep_sod_append.do',
        deps=[
            out_data('sod_2007.dta'),
            out_data('sod_2008.dta'),
            out_data('sod_2009.dta'),
            out_data('sod_2010.dta'),
            out_data('sod_2011.dta'),
            out_data('sod_2012.dta'),
            out_data('sod_2013.dta'),
            out_data('sod_2014.dta'),
            out_data('sod_2015.dta'),
            out_data('sod_2016.dta'),
            out_data('sod_2017.dta')
        ],
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_prep_sod_append.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'sod.dta')
        ],
    )

    ctx(
        features='run_py_script',
        source='data_prep_gdp.py',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'SAGDP2N__ALL_AREAS_1997_2017.csv'),
            ctx.path_to(ctx, 'IN_MODEL_SPECS', 'state_names.json')
        ],
        target=ctx.path_to(ctx, 'OUT_DATA', 'gdp.dta'),
        name='data_prep_gdp'
    )

    ctx(
        features='run_py_script',
        source='data_prep_pi.py',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'SAINC1_1998_2017_ALL_AREAS.csv'),
            ctx.path_to(ctx, 'IN_MODEL_SPECS', 'state_names.json')
        ],
        target=ctx.path_to(ctx, 'OUT_DATA', 'pi.dta'),
        name='data_prep_pi'
    )

    ctx(
        features='run_py_script',
        source='data_prep_internet.py',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'ntia-analyze-table.csv'),
            ctx.path_to(ctx, 'IN_MODEL_CODE', 'data_cleaner.py')
        ],
        target=ctx.path_to(ctx, 'OUT_DATA', 'internet.dta'),
        name='data_prep_internet'
    )
