#! python


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_figures(*args):
        return ctx.path_to(ctx, 'OUT_FIGURES', *args)

    def out_tables(*args):
        return ctx.path_to(ctx, 'OUT_TABLES', *args)

    for model in 'baseline', 'max_moves_2':

        ctx(
            features='run_py_script',
            source='plot_locations.py',
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'schelling_{}.pickle'.format(model)),
                ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
            ],
            target=ctx.path_to(ctx, 'OUT_FIGURES', 'schelling_{}.png'.format(model)),
            append=model,
            name='plot_locations_{}'.format(model)
        )

    for table in 'table1_sumstat', 'table2_corr':

        ctx(
            features='run_do_script',
            source='{}.do'.format(table),
            deps=[
                out_data('data_all.dta')
            ],
            target=[
                out_tables('log', '{}.log').format(table),
                out_tables('{}.tex'.format(table))
            ],
        )

    # from src.final.project_dependency_graph import make_project_dependency_graph

    # ctx.add_post_fun(make_project_dependency_graph)
