#! python


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)

    for model in 'reg1_panel', 'reg2_compare', 'reg3_robustness':

        ctx(
            features='run_do_script',
            source='{}.do'.format(model),
            deps=[
                out_data('data_all.dta'),
                out_models('{}.do'.format(model))
            ],
            target=[
                out_analysis('log', '{}.log'.format(model)),
                out_analysis('{}.tex'.format(model))
            ],
        )
